services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: setlix/app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/setlix-dev
    networks:
      - setlix-net
  mysql:
    image: mysql:8.0
    ports:
      - "3306:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - setlix_mysql:/var/lib/mysql
    networks:
      - setlix-net
  redis:
    image: redis:alpine
    volumes:
      - setlix_redis:/data
    networks:
      - setlix-net
networks:
  setlix-net:
    driver: "bridge"
volumes:
  setlix_redis:
    driver: "local"
  setlix_mysql:
      driver: "local"
